### ISSUE TITLE
Consistant naming of citys (german/french)

### ISSUE THREAD

**Issue by PhoenixPhantom** [Sprudeel/SwissTopoLearner#6]
I don't know wheather this should really be concidered an issue but while all the cantons and citys are named in german throughout (and not in french for the French-speaking cantons) the two Citys "Delémont" and "Sion" are the only ones called by their french names and not their german ones "Delsberg" and "Sitten".
It irritates me a little bit but it's not really a big deal. 
Anyways, thank you very much for providing that awsome platform.
It really helps me a lot when practicing for the topograpy exam.

**Comment by Sprudeel** [comment]
Hey, thanks for the issue! I created this Learner specifically for our school, so the naming is according to our teaching material. If you want you can fork the project and create your own version of it. I will not be working on it, because I have a lot of other things to do in school.
I'm very happy to hear that it helped you.

**Comment by PhoenixPhantom** [comment]
Okay, that makes sense. Thanks for the suggestion.
